### ISSUE TITLE
Update the logging

### ISSUE THREAD

**Issue by alemanyp** [sonata-nfv/tng-slice-mngr#69]
Update the logs with the new LOGLEVEL described @jbonnet

**Comment by jbonnet** [comment]
@alemanyp, I think @mpeuster will be working on a Python version of this, which for sure will be easily re-usable on the Slice Manager...

**Comment by alemanyp** [comment]
cool!! i'll wait for it. @mpeuster do you need any help?

**Comment by mpeuster** [comment]
Yes, will build something for the packager: https://github.com/sonata-nfv/tng-sdk-package/issues/128

No help needed yet. Still planning. However, since the packager also runs in the SDK as a command line tool, I need to make the logging able to be used with two modes "SP-mode" as specified by José. And a "CLI-mode" to have nice colored outputs for the user. Maybe you don't need all of this for the slice manager.
Have to check the Python Custom Logging API first. Maybe I just overwrite the default logging methods.

**Comment by mpeuster** [comment]
@alemanyp I think I made up my mind about the design. I will basically create a slim wrapper for the default Python logger to get what we want.

Instead of:
```python
LOG = logging.getLogger(os.path.basename(__file__))
```

You will have: 

```python
LOG = TangoLogger(logging.getLogger(os.path.basename(__file__)))
```

and then all the Normal:

```python
LOG.info({"message": "hello world"})
```

It will automatically fill the JSON output with missing fields etc.

What do you think? Does something like this fit to your needs?

**Comment by jbonnet** [comment]
@mpeuster So `component` and `operation` get filled automaticaly?!? By-by, ruby, hello python!

**Comment by mpeuster** [comment]
Not sure, I operation is possible, but component yes. It is set when the logger in a module is initialized `os.path.basename(__file__))`

Current packager output already gives you the components:
 Example:
```
2018-11-15 15:20:10 [INFO] [packager.py] Packager done (0.3624s): TangoPackager(ae487322-d752-474a-b3fe-bf125938b01c)
2018-11-15 15:20:10 [DEBUG] [cli.py] Packager result: NapdRecord({'_project_wd': '/var/folders/yx/lvxqrl7j7954pkz6mmsh72br0000gn/T/tmp05272akx'
```

output is even colored ;-) I will see what I can automate and what not. Need to play a bit.

**Comment by jbonnet** [comment]
Ah, ok @mpeuster, I've opted to initiate the logger per container, with several `component`s....

**Comment by mpeuster** [comment]
Ok, ignore my comment above. I will do it with a custom logger implementation which is even more elegant.

Will be called like this:

```
LOG = TangoLogger.getLogger(__name__)
LOG.debug(....)
```

**Comment by mpeuster** [comment]
@jbonnet Ok, I think you want consider switching to Python ... besides the `operation`, I can even provide the `linenumber` and `threadName` automatically (without the developer changing any log command) ... :-P Python magic at its best ;-)

**Comment by jbonnet** [comment]
OMG... I think I could match that in Ruby, but I see my code already so much blottered... What I love in your proposed design is that `component` and `operation` is automatic (a plus over my proposed design), `lineno` could easily be added. I tend to avoid threading in as much as possible... :D

**Comment by mpeuster** [comment]
Yeah, threading is also not so important for me. But I think that the MANO framework guys might find it helpful.

I try to finalize this today and share it before I am out of office next week.

**Comment by mpeuster** [comment]
Ok, didn’t make it. Need to fix some bugs first. So it will be end of next week until you can use the code.

**Comment by mpeuster** [comment]
Done: https://github.com/sonata-nfv/tng-sdk-package/wiki/Python-based-5GTANGO-JSON-logging

I will send a mail in some minutes to the lists.

**Comment by alemanyp** [comment]
Logging added
